---
# Deploy Docker containers
# Usage: ansible-playbook containers.yml --ask-vault-pass
# Or:    ansible-playbook containers.yml --vault-password-file=../.vault_pass

- name: Deploy Docker Containers
  hosts: docker_vm
  vars_files:
    - vars/vault.yml
    - vars/users.yml
    - vars/docker-vars.yml

  roles:
    - role: docker
      become: true
    - role: containers
      become: true
