---
collections:
  - name: https://github.com/ansible-collections/ansible.posix.git
    type: git
    version: main
  - name: community.general
    version: ">=9.0.0"
  - name: community.docker
    version: ">=3.12.0"
