---
- name: Bootstrap (init user)
  hosts: all
  become: true
  remote_user: init
  vars:
    ansible_user: stanley
  vars_files:
    - vars/users.yml
    - vars/vault.yml
  roles:
    - role: bootstrap

- name: Mount SMB shares on Docker VMs
  hosts: docker_vm
  become: true
  vars_files:
    - vars/users.yml
    - vars/vault.yml
    - vars/docker-vars.yml
  tasks:
    - name: Setup SMB mounts
      block:
        - name: Install cifs-utils
          ansible.builtin.apt:
            name: cifs-utils
            state: present

        - name: Create SMB credentials file
          ansible.builtin.copy:
            dest: /root/.smbcredentials
            content: |
              username={{ smb_credentials.username }}
              password={{ smb_credentials.password }}
            mode: '0600'
            owner: root
            group: root
          no_log: true

        - name: Create media mount point
          ansible.builtin.file:
            path: "{{ container_media_root }}"
            state: directory
            mode: '0755'

        - name: Create temporary mount point
          ansible.builtin.file:
            path: "{{ container_temp_root }}"
            state: directory
            mode: '0755'

        - name: Mount media share via fstab
          ansible.posix.mount:
            src: "{{ smb_media_path }}"
            path: "{{ container_media_root }}"
            opts: "rw,vers=3,credentials=/root/.smbcredentials,uid={{ container_puid }},gid={{ container_pgid }},file_mode=0770,dir_mode=0770"
            fstype: cifs
            state: mounted

        - name: Mount temporary share via fstab
          ansible.posix.mount:
            src: "{{ smb_temp_path }}"
            path: "{{ container_temp_root }}"
            opts: "rw,vers=3,credentials=/root/.smbcredentials,uid={{ container_puid }},gid={{ container_pgid }},file_mode=0770,dir_mode=0770"
            fstype: cifs
            state: mounted

        - name: Create required subdirectories on temporary share
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            owner: "{{ container_puid }}"
            group: "{{ container_pgid }}"
            mode: '0770'
          loop:
            - "{{ container_temp_root }}/sabnzbd"
            - "{{ container_temp_root }}/qbittorrent"
