---
- name: Update all servers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: true
        autoclean: true

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for system updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

- name: Update Docker containers
  hosts: docker
  become: true
  tasks:
    - name: Find all docker-compose files
      ansible.builtin.find:
        paths: /docker
        patterns: "docker-compose.yml"
        recurse: yes
      register: compose_files

    - name: Pull and update docker containers
      community.docker.docker_compose_v2:
        project_src: "{{ item.path | dirname }}"
        pull: always
        state: present
        recreate: always
      loop: "{{ compose_files.files }}"
      when: compose_files.files | length > 0
      register: compose_update_results
      ignore_errors: yes

    - name: Prune unused Docker images
      community.docker.docker_prune:
        images: yes
        images_filters:
          dangling: false

    - name: Report container updates
      ansible.builtin.debug:
        msg: "Updated {{ compose_files.files | length }} docker-compose stacks"
      when: compose_files.files | length > 0
